version: "3.3"
services:
  frontend:
    image: "withignore"

    ports:
      - "3000:3000"

    volumes:
      - ./:/app/public

    env_file:
      - ./env/front.env

  mysql:
    image: mysql
    env_file:
      - ./env/mysql.env
